import * as z from 'zod';

const evidenceUiType = z
  .literal(['range', 'radio', 'checkbox', 'file', 'text', 'starter'])
  .meta({
    description: `
    - 'starter': For the initial question in a discussion evidence gatherer.
    - 'range': For measuring things (e.g. 1-10 satisfaction, or amount of items).
    - 'radio': For single choice answers (e.g. Yes/No).
    - 'checkbox': For multiple choice.
    - 'file': If they should upload a photo or document.
    - 'text': For open feedback.
    `,
  });

const evidenceQuestion = z.object({
  id: z
    .string()
    .meta({ description: 'Unique identifier for the question item' }),
  text: z.string().meta({ description: 'Label for the question item field' }),
  variant: evidenceUiType,
  options: z.array(z.string()).optional().meta({
    description:
      'Required for radio/checkbox. For range, provide two numbers: [min, max]. Empty for text/file/starter.',
  }),
  delta: z.number().meta({
    description:
      'The relative position of the question item within the evidence gatherer (e.g. 0 for the first question, 1 for the second, etc.).',
  }),
});

const evidenceType = z.literal(['structured', 'discussion']).meta({
  description: `
    - 'structured': Multiple questions presented within a form.
    - 'discussion': Open-ended discussion with a single starter question.
  `,
});

const evidenceAttributes = z.object({
  processing: z.record(z.string(), z.boolean().optional()).meta({
    description:
      'Indicates if content for the evidence gatherer is currently being generated.',
  }),
  ready: z.record(z.string(), z.boolean().optional()).meta({
    description:
      'Indicates if the content for the evidence gatherer is ready and available.',
  }),
});

const evidence = z.object({
  id: z.string(),
  variant: evidenceType,
  attributes: evidenceAttributes,
  framework: z.string().meta({
    description:
      'A description of the framework to use for generating the evidence gathering questions and/or starter question. If not specified, the Theory of Change will be used by default.',
  }),
  status: z.literal(['draft', 'active', 'archived']).meta({
    description:
      'The current status of the evidence gatherer (e.g. "draft", "active", "archived").',
  }),
  researchId: z.string().meta({
    description:
      'The identifier of the research project this evidence gatherer belongs to.',
  }),
  smartscriptId: z.string().meta({
    description:
      'The data gathering smartscript autogenerated using the items listed in this evidence gatherer.',
  }),
  title: z.string().meta({
    description:
      'The title of the evidence gatherer, e.g. "Customer Feedback".',
  }),
  description: z.string().optional().meta({
    description: 'Additional details or context about the evidence gatherer.',
  }),
});

export type ResearchEvidence = z.infer<typeof evidence>;
export type ResearchEvidenceType = z.infer<typeof evidenceType>;
export type ResearchEvidenceQuestionItem = z.infer<typeof evidenceQuestion>;
export type ResearchEvidenceUiType = z.infer<typeof evidenceUiType>;
export type ResearchEvidenceAttributes = z.infer<typeof evidenceAttributes>;
export {
  evidence,
  evidenceType,
  evidenceQuestion,
  evidenceUiType,
  evidenceAttributes,
};
