import * as z from 'zod';

const evidenceUiType = z
  .literal(['range', 'radio', 'checkbox', 'file', 'text'])
  .meta({
    description: `
    - 'range': For measuring things (e.g. 1-10 satisfaction, or amount of items).
    - 'radio': For single choice answers (e.g. Yes/No).
    - 'checkbox': For multiple choice.
    - 'file': If they should upload a photo or document.
    - 'text': For open feedback.
    `,
  });

const evidenceQuestionItem = z.object({
  id: z
    .string()
    .meta({ description: 'Unique identifier for the question item' }),
  text: z.string().meta({ description: 'Label for the question item field' }),
  variant: evidenceUiType,
  options: z.array(z.string()).optional().meta({
    description:
      'Required for radio/checkbox. For range, provide two numbers: [min, max]. Empty for text/file.',
  }),
});

const evidenceType = z.literal(['structured', 'discussion']).meta({
  description: `
    - 'structured': Multiple questions presented within a form.
    - 'discussion': Open-ended discussion with a single starter question.
  `,
});

const evidence = z.object({
  id: z.string(),
  variant: evidenceType,
  framework: z.string().meta({
    description:
      'A description of the framework to use for generating the evidence gathering questions and/or starter question. If not specified, the Theory of Change will be used by default.',
  }),
  items: z.array(evidenceQuestionItem).optional().meta({
    description: 'Required for structured variant.',
  }),
  starterQuestion: z
    .string()
    .optional()
    .meta({ description: 'Required for discussion variant.' }),
  smartscriptId: z.string().meta({
    description:
      'The data gathering smartscript autogenerated using the items listed in this evidence gatherer.',
  }),
  title: z.string().meta({
    description:
      'The title of the evidence gatherer, e.g. "Customer Feedback".',
  }),
  description: z.string().optional().meta({
    description: 'Additional details or context about the evidence gatherer.',
  }),
});

export type ResearchEvidence = z.infer<typeof evidence>;
export type ResearchEvidenceType = z.infer<typeof evidenceType>;
export type ResearchEvidenceQuestionItem = z.infer<typeof evidenceQuestionItem>;
export type ResearchEvidenceUiType = z.infer<typeof evidenceUiType>;
export { evidence, evidenceType, evidenceQuestionItem, evidenceUiType };
