import * as z from 'zod';

const evidenceUiType = z
  .literal(['range', 'radio', 'checkbox', 'file', 'text'])
  .meta({
    description: `
    - 'range': For measuring things (e.g. 1-10 satisfaction, or amount of items).
    - 'radio': For single choice answers (e.g. Yes/No).
    - 'checkbox': For multiple choice.
    - 'file': If they should upload a photo or document.
    - 'text': For open feedback.
    `,
  });

const evidenceQuestionItem = z.object({
  id: z
    .string()
    .meta({ description: 'Unique identifier for the question item' }),
  text: z.string().meta({ description: 'Label for the question item field' }),
  variant: evidenceUiType,
  options: z.array(z.string()).optional().meta({
    description:
      'Required for radio/checkbox. For range, provide two numbers: [min, max]. Empty for text/file.',
  }),
});

const evidenceType = z.literal(['structured', 'discussion']).meta({
  description: `
    - 'structured': Multiple questions presented within a form.
    - 'discussion': Open-ended discussion with a single starter question.
  `,
});

const evidence = z.object({
  variant: evidenceType,
  items: z.array(evidenceQuestionItem).optional().meta({
    description: 'Required for structured variant.',
  }),
  starterQuestion: z
    .string()
    .optional()
    .meta({ description: 'Required for discussion variant.' }),
  smartscriptIds: z.array(z.string()).meta({
    description: 'A list of smartscripts used to gather data from the user or to prepare the user for the process of gathering data.'
  }),
  dataSmartscriptId: z.string().meta({
    description: 'The main data gathering smartscript autogenerated using the items listed in this evidence gatherer.'
  }),
});

export type Evidence = z.infer<typeof evidence>;
export type EvidenceType = z.infer<typeof evidenceType>;
export type EvidenceQuestionItem = z.infer<typeof evidenceQuestionItem>;
export type EvidenceUiType = z.infer<typeof evidenceUiType>;
export { evidence, evidenceType, evidenceQuestionItem, evidenceUiType };
